Adjust assertion of max_error_length test
collective/icalendar pull request #480
Opened 2022-10-30 04:57 UTC by angatha

Some message parts may be hidden from the assertion because of multiple splitting. See #473 and [this](https://github.com/collective/icalendar/pull/473/files)for context.

2022-10-30 08:33 UTC, jacadzaca approved these changes

2022-10-30 08:35 UTC, jacadzaca commented
Good catch :)

2022-10-30 08:38 UTC, jacadzaca commented
@angatha could you provide an example file ics with a ': ' and add it to the parameter list? e.g:

```
BEGIN:VCALENDAR
BEGIN:VEVENT
SUMMARY:Example calendar with a ': ' in the summary
END:VEVENT
BEGIN:VEVENT
SUMMARY:Another event with a ': ' in the summary
END:VEVENT
[...]
END:VCALENDAR
```

2022-10-30 08:39 UTC, jacadzaca requested changes
@angatha could you provide an example file ics with a ': ' and add it to the parameter list? e.g:

```
BEGIN:VCALENDAR
BEGIN:VEVENT
SUMMARY:Example calendar with a ': ' in the summary
END:VEVENT
BEGIN:VEVENT
SUMMARY:Another event with a ': ' in the summary
END:VEVENT
[...]
END:VCALENDAR
```

2022-10-30 09:36 UTC, angatha commented
I can do that. The one that you provided, is a good reference, but I'm missing the advantage of that.

Assuming the state of #473, that test would succeed. And assuming the state before #473, where long messages where generated, that test will still pass, since the error is in the test itself.

The fact, that the test succeeds, indicates the bug inside the test but no one will notice this since all tests passed.

2022-10-30 09:37 UTC, jacadzaca commented
Oh, you're right.

2022-10-30 09:38 UTC, jacadzaca approved these changes

2022-10-30 09:39 UTC, angatha commented
But it doesn't hurt :)

2022-10-30 09:41 UTC, jacadzaca commented
maybe we should assert that the message is split as we think in the test? or would that be testing tests esentialy?

2022-10-31 08:16 UTC, niccokunzmann commented
Tests are different from contracts or verifications or proofs of programs. They are a heuristic. If they fail, something is wrong if they don't, we do not know. I think, we are hitting that here.

2022-10-31 08:17 UTC, niccokunzmann commented
It looks good to me  merging.

2022-10-31 08:17 UTC, merged