Extend the existing example with alarms and recurrence-rule
collective/icalendar pull request #613
Opened 2024-05-01 17:29 UTC by bastianwegge

As described in #612 I struggled a little and read parts of the awesome library code and the RFC to understand how to do alerting and recurrence. This PR aims to extend the existing example a little for upcoming visitors.

I saw that there is a `test_examples.py` that does what parts of the examples do but it looks a little different. If you want me to adjust the test in this PR, @jacadzaca  please feel free to drop a comment.

2024-05-01 23:55 UTC, stevepiercy requested changes
Just a few nitpicks, and LGTM. Thank you!

2024-05-01 23:55 UTC, stevepiercy commented on CHANGES.rst
> +- Extend examples with alarm + recurrence
```suggestion
- Extend examples in Usage with alarm and recurrence
```

2024-05-01 23:55 UTC, stevepiercy commented on docs/usage.rst
> +Extending the event with subcomponents you can create multiple alarms::
```suggestion
By extending the event with subcomponents, you can create multiple alarms::
```

2024-05-01 23:55 UTC, stevepiercy commented on docs/usage.rst
> +  >>> alarm_1h_before.add("description", 'Reminder: Event in 1 hour')
```suggestion
  >>> alarm_1h_before.add("description", "Reminder: Event in 1 hour")
```

2024-05-01 23:55 UTC, stevepiercy commented on docs/usage.rst
> +  >>> alarm_24h_before.add("description", 'Reminder: Event in 24 hours')
```suggestion
  >>> alarm_24h_before.add("description", "Reminder: Event in 24 hours")
```

2024-05-01 23:55 UTC, stevepiercy commented on docs/usage.rst
> +  >>> event.add('rrule', {'freq': 'daily'})
```suggestion
  >>> event.add("rrule", {"freq": "daily"})
```

2024-05-02 08:46 UTC, bastianwegge commented
@stevepiercy I just noticed that I used double-quotes in the new examples and the rest uses single quotes. I'm gonna quickly fix that as well.

2024-05-02 09:15 UTC, bastianwegge commented
Feel free to merge or to request changes again. Thanks for your feedback!

2024-05-02 09:24 UTC, stevepiercy approved these changes
Consistency is good.

If this package adopts Black for formatting code and examples, though...

2024-05-02 09:30 UTC, stevepiercy commented
I requested reviews from a few top maintainers who can do a release on PyPI. Thanks for the contribution!

2024-05-02 11:34 UTC, jacadzaca approved these changes

2024-05-03 17:44 UTC, thet approved these changes
This looks good to me. Thanks for the contribution!

2024-05-03 19:18 UTC, merged

2024-05-03 19:19 UTC, niccokunzmann commented
Thanks!