Rename master to main in docs
collective/icalendar pull request #633
Opened 2024-06-20 13:28 UTC by niccokunzmann

We switched to `main`, see #627.

2024-06-20 21:28 UTC, stevepiercy requested changes
I found one more, but I assume I cannot push to your remote.

## usage.rst

```diff
- Have a look at the `tests <https://github.com/collective/icalendar/tree/master/src/icalendar/tests>`__ of this package to get more examples.
+ Have a look at the `tests <https://github.com/collective/icalendar/tree/main/src/icalendar/tests>`__ of this package to get more examples.
```

2024-06-20 21:28 UTC, stevepiercy commented on CHANGES.rst
There are two other historical references to `master` in this file. I don't know whether it makes sense to rename them to `main`, but I think now that `master` is gone, it would be good to rename those obsolete references as well. It is the right thing to do and it would point developers in the right direction.

BTW, Juneteenth was yesterday, June 19. It's a holiday that commemorates the ending of slavery in the United States in 1865. But 159 years later, we still have slavery. The 13th Amendment to the US Constitution has a loophole which allows slavery "as a punishment for crime". People of color are disproportionately imprisoned in the US, often for trivial crimes, in our flawed legal system. There is a movement to remove this disgraceful loophole with the [Abolition Amendment](https://www.merkley.senate.gov/ahead-of-juneteenth-merkley-williams-propose-constitutional-amendment-to-close-slavery-loophole-in-13th-amendment-2021/).

2024-06-21 16:58 UTC, niccokunzmann commented on CHANGES.rst
I changed the link in c29074d.

Could you point out the other references to master?

I see some in the changelog but I would leave them until someone would like to rewrite history.

2024-06-21 21:34 UTC, stevepiercy commented on CHANGES.rst
In `CHANGES.rst`.

Line 328:

```
  The master branch will be for the remaining Python versions that we support.
```

Line 968

```
  documentation is generated on each commit (for master). Documentation can be
```

2024-06-21 21:36 UTC, stevepiercy commented on CHANGES.rst
I use PyCharm for my IDE. It categorizes found items (comments, code, strings), and I sometimes miss items because I don't dig deeper.

2024-06-22 16:28 UTC, niccokunzmann commented on CHANGES.rst
It probably does not hurt to change this.

2024-06-22 16:45 UTC, niccokunzmann commented on CHANGES.rst
Changelog changed in 752928c.

2024-06-22 17:04 UTC, niccokunzmann commented
The coverage report is failing.

```
Submitting coverage to coveralls.io...
Error running coveralls: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/coveralls/api.py", line 298, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/coveralls/cli.py", line 98, in main
    result = coverallz.wear()
Received 422 submitting job via Github Actions. By default, coveralls-python uses the "github" service name, which requires you to set the $GITHUB_TOKEN environment variable. If you want to use a COVERALLS_REPO_TOKEN instead, please manually override $COVERALLS_SERVICE_NAME to "github-actions". For more info, see https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/coveralls/api.py", line 275, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/coveralls/api.py", line 301, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

```

2024-06-22 20:16 UTC, stevepiercy approved these changes
Approved, pending resolution of 422 with Coveralls. See https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support for possible solutions.

2024-06-23 13:41 UTC, merged