Make coverage report submission optional for test runs
collective/icalendar pull request #644
Opened 2024-06-22 17:11 UTC by niccokunzmann

The coverage report submission can break.
This makes the tests fail.
Coverage is still computed and tests run with this PR.

This is my attempt: If the submission fails, that is ok. Not the PR's fault!

Context:

- https://github.com/collective/icalendar/actions/runs/9626921659/job/26553447797#step:6:98
- https://github.com/collective/icalendar/pull/633#issuecomment-2184110223

2024-06-22 20:14 UTC, stevepiercy requested changes

2024-06-22 20:14 UTC, stevepiercy commented on .github/workflows/tests.yml
https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support proposes several different fixes for the 422 error messages. It looks like we have a mixture of the first two methods, which are in conflict with each other.

2024-06-23 14:02 UTC, niccokunzmann commented on .github/workflows/tests.yml
Nice. I will try something out... We actually use a parallel build, so I changed the code.

2024-06-23 14:49 UTC, niccokunzmann commented
coverage reporting works

2024-06-24 04:47 UTC, stevepiercy approved these changes
LGTM. OK to merge, pending resolution of todo checklist in original pull request description.

2024-06-24 18:26 UTC, niccokunzmann commented
I changed the description to represent the change.

2024-06-25 10:13 UTC, stevepiercy approved these changes

2024-06-25 10:14 UTC, stevepiercy commented
@niccokunzmann I'll let you manage merging of PRs as it is a moving target for me and I reckon you have a better grip on it.

2024-06-25 10:42 UTC, niccokunzmann commented
I would like to you feel confident to merge. It is part of empowering contributors and spreading the load and increasing the bus factor, diversity, ... .

Here are your documented rights:
https://icalendar.readthedocs.io/en/latest/maintenance.html#collaborators

Please use them :heart:

2024-06-25 10:44 UTC, niccokunzmann commented
Ah and most important: Merging makes people happy! And we have a version control system, so we do not really cause irreversible damage. Trust first if you ask me.

2024-06-25 12:18 UTC, merged