[WIP] RFC 7529
collective/icalendar pull request #667
Opened 2024-06-26 23:01 UTC by niccokunzmann

This tests and adds compatibility to RFC 7529.

2024-06-29 16:28 UTC, niccokunzmann commented
This is ready to review and merge.

2024-06-30 00:00 UTC, stevepiercy requested changes
Trivial formatting fixes, and a couple of questions.

2024-06-30 00:00 UTC, stevepiercy commented on CHANGES.rst
> +  component and returns ``True``/``False``.
```suggestion
  component and returns ``True`` or ``False``.
```

2024-06-30 00:00 UTC, stevepiercy commented on docs/usage.rst
Do we have a docs pull request preview, such as that provided by Read the Docs? It would be good to verify that RFC links, API docs, and other markup renders correctly, without pulling down the branch and building the docs locally.

If not, we could copy what I did for [`plone-sphinx-theme`](https://github.com/plone/plone-sphinx-theme/blob/main/.github/workflows/rtd-pr-preview.yml). See also https://github.com/plone/plone-sphinx-theme/blob/main/.readthedocs.yaml#L13-L25 and https://github.com/plone/plone-sphinx-theme/blob/main/Makefile#L215-L217 for complete example.

2024-06-30 00:00 UTC, stevepiercy commented on src/icalendar/parser_tools.py
> +def to_unicode(value:ICAL_TYPE, encoding='utf-8') -> str:
I would expect a linter to catch space inconsistencies.

```suggestion
def to_unicode(value: ICAL_TYPE, encoding='utf-8') -> str:
```

2024-06-30 00:00 UTC, stevepiercy commented on src/icalendar/parser_tools.py
> +def data_encode(data:Union[ICAL_TYPE, dict, list], encoding=DEFAULT_ENCODING) -> bytes:
```suggestion
def data_encode(data: Union[ICAL_TYPE, dict, list], encoding=DEFAULT_ENCODING) -> bytes:
```

2024-06-30 22:03 UTC, niccokunzmann commented on docs/usage.rst
This is an issue now: https://github.com/collective/icalendar/issues/669

2024-06-30 23:02 UTC, stevepiercy approved these changes
LGTM, although the specific RFC details are over my head. But I reckon if there's a problem with its implementation, then someone will let us know. 😁

2024-07-01 22:27 UTC, niccokunzmann commented
@jacadzaca would you like to have a look, too?

2024-07-03 13:46 UTC, merged