Document Debian package
collective/icalendar pull request #718
Opened 2024-10-09 08:07 UTC by niccokunzmann

This fixes #701

2024-10-15 22:51 UTC, stevepiercy requested changes
Minor touch-up

2024-10-15 22:51 UTC, stevepiercy commented on CHANGES.rst
> +- Document the Debian package, see `Issue 701 <https://github.com/collective/icalendar/issues/701>`_
```suggestion
- Document the Debian package. See `Issue 701 <https://github.com/collective/icalendar/issues/701>`_.
```

2024-10-15 22:51 UTC, stevepiercy commented on docs/install.rst
> +Debian/Ubuntu
```suggestion
Debian or Ubuntu
```

2024-10-15 22:51 UTC, stevepiercy commented on docs/install.rst
> +-------------
```suggestion
----------------
```

2024-10-15 22:51 UTC, stevepiercy commented on docs/install.rst
> +for Debian and derivatives.
```suggestion
for Debian or its derivatives.
```

2024-10-16 11:25 UTC, niccokunzmann commented
Thanks for the documentation review! I assume it is ok to merge when the tests pass...

2024-10-16 11:31 UTC, merged