Ruff format tests
collective/icalendar pull request #719
Opened 2024-10-09 08:51 UTC by niccokunzmann

This is a contribution to #672 and formats the test files.

Some errors are still in the tests files. I started with formatting these as they likely do not cause merge conflicts for future contributions.

2024-10-15 15:05 UTC, niccokunzmann commented
@jacadzaca, if you have time, please review it.
@stevepiercy, this is for #672 in which we had a discussion about code styling.

2024-10-16 00:07 UTC, stevepiercy requested changes
Proper grammar on change log. If tests pass, LGTM!

2024-10-16 00:07 UTC, stevepiercy commented on CHANGES.rst
> +- Ruff format test code, see `Issue 672 <https://github.com/collective/icalendar/issues/672>`_
```suggestion
- Format test code with Ruff. See `Issue 672 <https://github.com/collective/icalendar/issues/672>`_.
```

2024-10-16 11:17 UTC, niccokunzmann commented
@stevepiercy Thanks for the review! When the tests pass, I will merge it.

2024-10-16 11:34 UTC, merged