Add docs folder
collective/icalendar pull request #720
Opened 2024-10-10 11:14 UTC by niccokunzmann

fixes #712

> To Reproduce -> These commands work now. The docs are added.

2024-10-10 11:15 UTC, niccokunzmann commented
@mgorny, I had a look and it turns out the fix is simple.

2024-10-10 12:07 UTC, mgorny commented
Thanks!

2024-10-11 11:26 UTC, niccokunzmann commented
@stevepiercy would you like to have a look? You like the docs, too :)

2024-10-11 22:57 UTC, stevepiercy requested changes
I like grammatically correct sentences using the past verb tense in change log notes, because after publication it will be in the past.

Also I like error messages to tell me both what the problem is and what explicit action I need to do next to resolve it.

Thanks for asking for my review.

2024-10-11 22:57 UTC, stevepiercy commented on CHANGES.rst
> +- Add missing ``docs`` folder to distribution packages, see `Issue 712 <https://github.com/collective/icalendar/issues/712>`_
```suggestion
- Added missing ``docs`` folder to distribution packages. See `Issue 712 <https://github.com/collective/icalendar/issues/712>`_.
```

2024-10-11 22:57 UTC, stevepiercy commented on src/icalendar/tests/test_create_release.sh
> +  echo "ERROR: The documentation is not included in the release."
```suggestion
  echo "ERROR: The documentation is not included in the release, but should be."
```

2024-10-12 13:42 UTC, niccokunzmann commented
@stevepiercy thanks for the review! I agree with the error messages being more of a guide.

When it comes to the changelog. My reasoning behind present tense is this:

In some practice, commits are formulated in this way: 
Apply this commit to <commit message>
.... Log changes
.... Add feature
.... Remove error
There, it is a bit imperative present tense. So, the changelog can be close to that but I really do not mind how people write their changelog as long as it is descriptive enough - very vague.

I value the contribution, contributions from a diverse background are divers. Asking to conform and make lots of changes might not be as inclusive when it comes to time invested voluntarily.

Feel free to merge as I would not add anything... I just have to wait for 1 week to merge my own PR.

2024-10-13 10:03 UTC, stevepiercy approved these changes
LGTM. Thanks for the explanation of change log policy.

2024-10-13 12:02 UTC, merged