Add calculation of alarm times
collective/icalendar pull request #737
Opened 2024-10-25 11:14 UTC by niccokunzmann

This contributes to #716 by adding an `icalendar.Alarms` module.
This module allows calculating the alarm times.
It has been tested with

- RFC 9074
- Google
- Outlook
- Nextcloud
- Thunderbird
- Etar

TODO:

- [ ] simple interface in Todo and Event
- [ ] fix `# TODO:` comments
- [ ] add changelog entry
- [ ] implement tests that are todo

2024-11-02 13:22 UTC, niccokunzmann commented
@stevepiercy, could you review the docs?
@jacadzaca, do you have time to have a look at this?

2024-11-03 12:35 UTC, stevepiercy commented
@niccokunzmann FYI, I'm backlogged and slammed with preparation for [PloneConf 2024](https://2024.ploneconf.org/en). I estimate it will be at least a week until I can review icalendar PRs.

2024-11-07 13:08 UTC, stevepiercy requested changes
I caught only a few typos and Oxford comma issues. This is an excellent feature.

I approve once you review and make the changes.

2024-11-07 13:08 UTC, stevepiercy commented on CHANGES.rst
> +- Add ``Alarm.ACKNOWLEDGED``, ``Alarm.TRIGGER``, ``Alarm.REPEAT`` and ``Alarm.DURATION`` properties
```suggestion
- Add ``Alarm.ACKNOWLEDGED``, ``Alarm.TRIGGER``, ``Alarm.REPEAT``, and ``Alarm.DURATION`` properties
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/alarms.py
> +        E.g. in some calendar software, this is True until the user had a look
```suggestion
        For example, in some calendar software, this is True until the user looks
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/alarms.py
> +        E.g. Thunderbird and Google Calendar store the last time
```suggestion
        For example, Thunderbird and Google Calendar store the last time
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/alarms.py
> +        All alarms that happen before this time count as ackknowledged.
```suggestion
        All alarms that happen before this time count as acknowledged.
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/tools.py
> +    pytz requires this funtion to be used in order to correctly calculate the
```suggestion
    pytz requires this function to be used in order to correctly calculate the
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/tests/test_pytz_zoneinfo_integration.py
> +    """Check that the provider name is ok."""
```suggestion
    """Check that the provider name is OK."""
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/tests/test_issue_716_alarm_time_computation.py
> +DTSTART, DTEND and DURATION.
```suggestion
DTSTART, DTEND, and DURATION.
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +    When an alarm is triggered on a client, clients can check to see if an"ACKNOWLEDGED"
```suggestion
    When an alarm is triggered on a client, clients can check to see if an "ACKNOWLEDGED"
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +        RDATE, EXDATE and RRULE properties.
```suggestion
        RDATE, EXDATE, and RRULE properties.
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +        RDATE, EXDATE and RRULE properties.
```suggestion
        RDATE, EXDATE, and RRULE properties.
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +        Note that this only uses DTSTART and DTEND but ignores
```suggestion
        Note that this only uses DTSTART and DTEND, but ignores
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +        Note that this only uses DTSTART and DUE but ignores
```suggestion
        Note that this only uses DTSTART and DUE, but ignores
```

2024-11-07 13:08 UTC, stevepiercy commented on src/icalendar/cal.py
> +        """Whether this component has attributes that indicate that Mozilla Thunderbird createsd it."""
```suggestion
        """Whether this component has attributes that indicate that Mozilla Thunderbird created it."""
```

2024-11-14 11:28 UTC, niccokunzmann commented
@stevepiercy Thanks for reviewing the docs!

After I merging this, I will use the functionality for recurring-ical-events to calculate if an alarm happens within a time span.
I might come back with improvements in follow-up PRs.

2024-11-14 11:46 UTC, niccokunzmann commented
Thanks for the review again! The tests pass and I added all your suggestions. Merging ...

2024-11-14 11:46 UTC, merged