This adds generating VTIMEZONE components from tzinfo objects
collective/icalendar pull request #741
Opened 2024-11-02 16:15 UTC by niccokunzmann

Fixes #722

2024-11-10 14:16 UTC, niccokunzmann commented
I run a bit into an issue here.

I can generate them successfully for zoneinfo/dateutil.
However, when I use pytz, I run into a strange error (VTIMEZONE component != VTIMEZONE component)

    pytz -> VTIMEZONE -> pytz -> VTIMEZONE

changes the transition times.

Here VTIMEZONE == VTIMEZONE

    zoneinfo -> VTIMEZONE -> dateutil -> VTIMEZONE

Since these yield the same result (VTIMEZONE == VTIMEZONE):

    pytz -> VTIMEZONE
    zoneinfo -> VTIMEZONE

I conclude that `VTIMEZONE -> pytz` is actually a bit problematic. I will check this. In this case, `icalendar` had a bug around the transition day that the time was moved a little. e.g.

- Europe/Berlin transitions at 3:00am/2:00am and our pytz implementation turns it into 4:00/0:00
- Amerika/New_York transitions at 3:00am/1:00am and our pytz implementation turns it into 4:00/0:00
- Asia/Singapore transitions at 19820101T000000 and our pytz implementation turns it into 19820101T003000 = +30min

Next steps:

- [ ] isolate the cause of the difference
- [ ] fix the mistake if it is ours

So, in case I can  this and you depend on pytz, I still recommend that you upgrade

2024-11-11 00:51 UTC, niccokunzmann commented
I think, the interface I would like to use is this one:

    Calendar().add_missing_timezones()

This will then add all the missing timezones automatically to the calendar.

2024-11-11 11:36 UTC, stevepiercy requested changes
LGTM, except for one param description.

2024-11-11 11:36 UTC, stevepiercy commented on src/icalendar/cal.py
> +                 None for pytz and zoneinfo is fine.
This param description doesn't make sense to me. Is it two sentences?

2024-11-11 12:26 UTC, niccokunzmann commented
The pytz parsing seems to fail when we check two calendars for equality.

```
   def assert_equal(actual_value, expected_value):
        """Make sure both values are equal"""
>       assert actual_value == expected_value
E       AssertionError: assert VCALENDAR({},...TE-TIME'}))})) == VCALENDAR({},...TE-TIME'}))}))
E         
E         Use -v to get more diff

src/icalendar/tests/test_equality.py:33: AssertionError
---------------------------- Captured stdout setup -----------------------------
example file: issue_722_timezone_transition_ambiguity.ics
```

2024-11-12 15:18 UTC, niccokunzmann commented on src/icalendar/cal.py
> +                 None for pytz and zoneinfo is fine.
I changed the description.
https://github.com/collective/icalendar/pull/741/files#diff-209244e93cf08598138afbd0965d624109c7a013acabe550af7322aa36078f30R1131

2024-11-12 22:38 UTC, stevepiercy requested changes
A few grammar fixes, and comments.

2024-11-12 22:38 UTC, stevepiercy commented on src/icalendar/tests/test_issue_722_generate_vtimezone.py
> +    """Sometimes, times can be ambiguous: We go back from 3am to 2 am.
Although those who work with datetime and DST shifts have the experience of being bitten by this, we should explain it in detail. The explanation might also be helpful in the narrative docs, but I'm not sure where. There are also some really good PyCon videos and talks that discuss working with datetime.

```suggestion
    """When going from Daylight Saving Time to Standard Time, times can be ambiguous.
    For example, at 3:00 AM, the time falls back to 2:00 AM, repeating a full hour of times from 2:00 AM to 3:00 AM on the same date.
```

2024-11-12 22:38 UTC, stevepiercy commented on src/icalendar/tests/test_issue_722_generate_vtimezone.py
> +    create a timezone that allows being after of cause.
I'm not sure what this sentence was trying to say, so this is my best guess. Please alter as needed.

```suggestion
    create a timezone that allows the event to be after this ambiguous time span, of course.
```

2024-11-12 22:38 UTC, stevepiercy commented on src/icalendar/cal.py
> +        In order to createa :rfc:`5545` compatible calendar,
```suggestion
        To create a :rfc:`5545` compatible calendar,
```

2024-11-21 18:56 UTC, niccokunzmann commented
Thank you for your reviews! I think this is ready now for the last review. The most important functionality has been added which allows us to add missing VTIMEZONE components to the calendar.

2024-11-22 00:07 UTC, stevepiercy approved these changes

2024-11-22 11:44 UTC, merged